
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lab rpl 1
 */
public class LaundryOk extends javax.swing.JFrame {

    /**
     * Creates new form LaundryOk
     */
    public LaundryOk() {
        initComponents();
    }
    
    public int Total;
    
    public void reset(){
    cmb_type.setSelectedItem("Select");
    txt_price.setText("");
    txt_weight.setText("");
    txt_total.setText("");
    txt_cash.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        btn_pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Laundry Oke");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txt_cash.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jPanel1.add(txt_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, 30));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel6.setText("Cash");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 30));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel7.setText("Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel8.setText("Price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel9.setText("Weight");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 30));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel10.setText("Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        txt_price.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, 30));

        txt_weight.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txt_weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_weightKeyReleased(evt);
            }
        });
        jPanel1.add(txt_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 30));

        txt_total.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, 30));

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dry Wash", "Wet Wash", "Iron" }));
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 30));

        btn_cancel.setBackground(new java.awt.Color(90, 165, 242));
        btn_cancel.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 130, -1));

        btn_pay.setBackground(new java.awt.Color(90, 165, 242));
        btn_pay.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btn_pay.setText("Pay");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 388, 425);

        setSize(new java.awt.Dimension(404, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        if(cmb_type.getSelectedItem().equals("Select")){
            txt_price.setText("0");
        } else if (cmb_type.getSelectedItem().equals("Dry Wash")){
            txt_price.setText("3000");
        } else if (cmb_type.getSelectedItem().equals("Wet Wash")){
            txt_price.setText("4000");
        }  else if (cmb_type.getSelectedItem().equals("Iron")){
            txt_price.setText("5000");
        }
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        if(txt_price.getText().isEmpty() || txt_weight.getText().isEmpty() || txt_total.getText().isEmpty() || txt_cash.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input Data!");
        } else {
            int cash = Integer.parseInt(txt_cash.getText());
            int changes = cash - Total;
            JOptionPane.showMessageDialog(null, "Your Changes is : \n" +changes);
            reset();
        }
    }//GEN-LAST:event_btn_payActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        reset();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_weightKeyReleased
        if(txt_weight.getText().equals("")){
            txt_total.setText("0");
        } else {
            int price = Integer.parseInt(txt_price.getText());
            float weight = Float.parseFloat(txt_weight.getText());
            Total = (int) (price*weight);
            txt_total.setText(String.valueOf(Total));
        }
    }//GEN-LAST:event_txt_weightKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaundryOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaundryOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaundryOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaundryOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaundryOk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_pay;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
